name: Validate JSON

on: [ push, pull_request ]

jobs:
  validate-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Syntax check
        uses: limitusus/json-syntax-check@v2.0.2
        with:
          pattern: "\\.json$"